name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 11

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew buildPlugin

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/mirai/*.jar"
          artifactContentType: application/jar
          tag: ${{ steps.vars.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
